# Generated by Django 4.2.6 on 2023-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
