# Generated by Django 4.2.6 on 2023-10-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Partida', '0001_initial'),
        ('Usuario', '__first__'),
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_transaccion', models.DateField(blank=True, null=True)),
                ('descripcion_transaccion', models.CharField(max_length=100)),
                ('debe_transaccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber_transaccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.cuenta')),
                ('n_partida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Partida.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
