# Generated by Django 4.2.6 on 2023-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('num_partida', models.IntegerField(default=0)),
            ],
        ),
    ]
